### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Maxiaojian66** [openjournals/brief-ideas#156]
Dear @physicsdavid and @arfon 
 I submitted a brief idea to the Journal of Brief Ideas and the title is "The applications of smart materials in the hydraulic machinery: the combination of piezoelectricity and bubbles".  It has been about a month since I submited my idea. But I did not recieve any letter from the system, even to reject my brief idea. So my question is -- has this idea been lost or is it really under review? I am sorry to bother you but I wanted to clarify what is going on. Thank you for any additional information you can provide. 
Best regards,
Xiaojian Ma

**Comment by physicsdavid** [comment]
Hi Xiaojian,

I actually had a question about your submission but wasn't able to find contact info for you. Specifically, there is a big section in the middle that appears to be formatted so that it looks like a quote from somewhere but it doesn't have a reference. Is that actually a quote or is it your writing? If we can resolve that, we can send it through the system.

Thanks,
David

**Comment by Maxiaojian66** [comment]
Dear @physicsdavid 

Thank you for your answer. I have re-written a new brief idea about the  smart materials, becasue I could not modify the old one, though I have read the suggestion from #84. In the new one, I reviewed some errors and added two co-authors. Please remove the old one from the website and send the new through the system.

Website about old idea:
http://beta.briefideas.org/ideas/744b9fa6919c22e855200ffb76ad0472

Website about new one:
 http://beta.briefideas.org/ideas/4f09be272f5698d2bba163393edbb7a1

Thank you for help and you can contact me at maxiaojian66@163.com without any hesitation, if you have any questions about this new idea.

Best Regards,
Xiaojian Ma
