### ISSUE TITLE
Idea submission

### ISSUE THREAD

**Issue by Ricardo-Bastos** [openjournals/brief-ideas#167]
Yesterday I submitted an idea and not only did I receive no confirmation, but the idea doesn't appear in the search nor in "Your ideas". I also sent a message through this form and got no response. To submit the idea, I clicked on "save". Should I have chosen another option? Or is there a prior filter by editors before final publication?

**Comment by arfon** [comment]
There is a second screen after the 'save' one which has the 'submit' button on. I think you must have missed this?

**Comment by Ricardo-Bastos** [comment]
I don't remember if I came up with this option the first time. Anyway, I repeated the submission. The last message I received says that the idea is pending acceptance by the editors of the Journal of Brief Ideas. My collection continues to appear as "empty" ("This user doesn't have any collections").
I appreciate your help!

**Comment by physicsdavid** [comment]
The way you phrased this, I am wondering if you are looking for the set of your own ideas or the concept of "collections" as we use them.

To see your own ideas, click on the menu at the top of the screen where it says "Your Ideas".

Collections are designed for you to put together a set of ideas from you or others into one group that can then be shared. To add to a collection, find the idea you want to add and click on the +Collect button on the right hand side in the "Actions" area. Then you can choose an existing collection or create a new one.

**Comment by gzampogna** [comment]
Gentlemen,

I am also experiencing the same issue as Ricardo-Bastos:  when I click the link to "Your Ideas," it states "There are no ideas currently. Would you like to create one?"  Is this because only your idea submissions which have been published actually appear in this list?

On a different subject:  What is the typical timeline for review and publication of idea submissions?  I submitted 8 separate ideas a couple weeks ago.  If you have any questions, please reach out to me.

I appreciate all the work you guys are doing here.
Thanks for the help.

Very respectfully,
GZ

**Comment by physicsdavid** [comment]
Hi GZ,

The "Your Ideas" list currently just shows the accepted ideas.

Apologies for the delay in having your submissions reviewed. With a purely volunteer group, things slow down over the year end/beginning. The papers have now been reviewed and entered in the system.

Regards,
David

**Comment by gzampogna** [comment]
Thanks for the reply, sir.
No worries; I understand.  And I appreciate the work you guys are doing.

VR,
Giulio
