### ISSUE TITLE
Handling citations within Brief Ideas

### ISSUE THREAD

**Issue by physicsdavid** [openjournals/brief-ideas#32]
What would you think of having citations within an idea exempt from the 200 word limit and referenced like this [1]. Then you could have a list of references as individual boxes to fill in either with a citation or DOI [2]. It would also be good to make it really easy to cite other brief ideas (and multiple brief ideas in one follow up idea). This would probably require that we have a search capability on the new idea entry page. (I'll talk about that in a separate issue though.)

[1] Reference 1
[2] Reference 2

**Comment by arfon** [comment]
OK, we've made a bunch of progress here and I'd like to review where we're at. I've made a quick screencast (below) that shows the current functionality.

![citations](https://cloud.githubusercontent.com/assets/4483/5592804/893146d8-91a9-11e4-8c98-93f256a3981b.gif)

To review, we currently support the following:

- We autocomplete references to internal (JOBI) ideas and users - this is achieved by typing the `#` and `@` characters respectively (:zap: @stuartlynn). These render out as _standard markdown links_.
- When the idea is created we [parse](https://github.com/openjournals/brief-ideas/blob/master/app/models/idea.rb#L42-L59) the text and search for references. If we match an internal JOBI Idea then we make a hard 'reference' to it which then shows up in the UI as 'Journal of Brief Idea References' underneath the paper.
- Other references are currently just links (see the link to the arXiv paper in the screencast). These are just normal links and we don't treat them in an particularly special way.

Questions about the current approach:

- We currently don't know the difference between a link to a paper or something that isn't a paper (unless it's a JOBI entity). Is this OK?
- Because of :point_up: we don't list the link to the arXiv paper in the references. This seems lame right?

We could encourage some kind of formatting such as `cite[Paper name](url to paper)` but after reading Martin Fenner's [post](http://blog.martinfenner.org/2013/06/19/citations-in-scholarly-markdown/) about this I'm inclined to keep them as 'standard' links and do something clever to parse out the links in a post processing step.

Anyway, I think we're in pretty good shape right now.

Thoughts @physicsdavid @stuartlynn @lnielsen ?

**Comment by physicsdavid** [comment]
I like the idea of keeping things as standard links and parsing out the links as a reference list at the end. However, there is one problem: what do you do for references that aren't online? How do we accommodate them - this could be important as not enough stuff, particularly old archived stuff, which could be very important for brief ideas, is on the open web.

**Comment by arfon** [comment]
> What do you do for references that aren't online? 

Good question... and to be honest I'm not sure I have a good answer right now. I feel like there's a whole bunch more we _could_ do here but it feels like a substantial amount of work to do this well.

My vote at this point would be to recognise this as a limitation of this first release and then look to implementing this if/when we get any traction.

What do you think?

**Comment by physicsdavid** [comment]
Yep, let's just have this as a limitation for now.

**Comment by arfon** [comment]
Closing this for now. We should revisit later.
