### ISSUE TITLE
Preview before publish?

### ISSUE THREAD

**Issue by arfon** [openjournals/brief-ideas#58]
Right now, there's no way to edit or preview an idea. Should we consider making new ideas 'drafts' until people click 'publish'?

/ cc @physicsdavid

**Comment by physicsdavid** [comment]
I'm in two minds because:
If you have preview, it adds a step that people are good at not following through on.
If you don't have preview, lots of typos will get through that might be caught.

However, given the finality of submitting (i.e. there is no way to edit something once submitted) then I think we should have preview.

**Comment by arfon** [comment]
> However, given the finality of submitting (i.e. there is no way to edit something once submitted) then I think we should have preview.

Agreed. I'll take a look into implementing this.

**Comment by stuartlynn** [comment]
The preview could be in a separate tag that the user can toggle like: http://markdownlivepreview.com/ or perhaps along side the input with it autoupdating like this : http://robdodson.github.io/mark-down/components/mark-down/demo.html

That way there wouldn't be an extra step but people could easily be able to see if it looks like they think it should
